keys:
  - &admin_david age1... # Replace with your Age Public Key
  - &host_yoga age1...   # Replace with Yoga's Age Public Key
  - &host_latitude age1... # Replace with Latitude's Age Public Key

creation_rules:
  - path_regex: secrets/hosts/yoga\.yaml$
    key_groups:
      - age:
          - *admin_david
          - *host_yoga
  - path_regex: secrets/hosts/latitude\.yaml$
    key_groups:
      - age:
          - *admin_david
          - *host_latitude
