keys:
  - &admin_david age1ff0ly0tej0yk39ycfq0dz0skmvqhe3tzuhdyaq2hkl52enu68sqqrr90s2
  - &host_yoga  age126lkzv0c60kqkva5qzmkuknlalgly93v4e3v7xwkwzrlq74mlvaqpl5kfs
  - &host_latitude age1n6s0w4k6p77220qhf3gjv29czcrsq3tpalwpualwveypm7wjtdpshtcd8g
  - &host_nix-media age1ntm37dt5h4qxqgv34ytjlw6wty560kzathxvlgp4gjx76s2ydc4qspjsm3

creation_rules:
  - path_regex: secrets/hosts/yoga\.yaml$
    key_groups:
      - age:
          - *admin_david
          - *host_yoga
  - path_regex: secrets/hosts/latitude\.yaml$
    key_groups:
      - age:
          - *admin_david
          - *host_latitude
  - path_regex: secrets/hosts/nix-media\.yaml$
    key_groups:
      - age:
          - *admin_david
          - *host_nix-media
