keys:
  - &admin_david age1... # Replace with Admin Public Key (generated in Step 1)
  - &host_yoga age1...   # Replace with Yoga Host Public Key (generated in Step 1)
  - &host_latitude age1... # Replace with Latitude Host Public Key (generated in Step 1)

creation_rules:
  - path_regex: secrets/hosts/yoga\.yaml$
    key_groups:
      - age:
          - *admin_david
          - *host_yoga
  - path_regex: secrets/hosts/latitude\.yaml$
    key_groups:
      - age:
          - *admin_david
          - *host_latitude
