{
  config,
  lib,
  ...
}:

let
  cfg = config.desktop.hyprland;

  # Hyprland 0.55+ Lua config. Ported from the old hyprlang dots
  # (~/Downloads/dots-main/hypr/hyprland.conf). The lucid-testing branch:
  # the Lucid shell (home/lucid.nix) replaces DMS as bar/launcher/lock/
  # notifications/idle — its keybinds, surface rules and glass layers are
  # loaded from the modules required near the end of this file.
  monitorLua = m: ''
    hl.monitor({
        output   = "${m.output}",
        mode     = "${m.mode}",
        position = "${m.position}",
        scale    = "${m.scale}",
    })
  '';

  monitorsLua =
    if cfg.monitors == [ ] then
      monitorLua {
        output = "";
        mode = "preferred";
        position = "auto";
        scale = "auto";
      }
    else
      lib.concatMapStrings monitorLua cfg.monitors;

  # Lid switch: internal panel off when closed, restored when opened (docked
  # use; logind still suspends per the laptop profile). Hyprland 0.55 moved
  # monitors into the Lua config parser, where `hyprctl keyword monitor ...`
  # is refused ("keyword can't work with non-legacy parsers") while still
  # exiting 0 — a silent no-op. The runtime path is `hyprctl eval` on
  # hl.monitor. Re-opening needs `hyprctl reload`: eval accepts
  # disabled=false but the panel stays off (verified 0.55.4); only a reload
  # re-applies the config's hl.monitor block and re-enables it.
  lidSwitchLua =
    if cfg.monitors == [ ] then
      ""
    else
      let
        m = builtins.head cfg.monitors;
      in
      ''
        hl.bind("switch:on:Lid Switch", hl.dsp.exec_cmd("hyprctl eval 'hl.monitor({output=\"${m.output}\", disabled=true})'"), { locked = true })
        hl.bind("switch:off:Lid Switch", hl.dsp.exec_cmd("hyprctl reload"), { locked = true })
      '';

  hyprlandLua = ''
    -- Generated by home-manager from home/hyprland.nix — do not edit.
    -- API reference: hyprland 0.55 Lua config (share/hypr/hyprland.lua in the
    -- hyprland package, wiki.hypr.land Configuring section).

    local terminal    = "${cfg.terminal}"
    local fileManager = "${cfg.fileManager}"
    local browser     = "${cfg.browser}"
    local mainMod     = "SUPER"

    -- Monitors
    ${monitorsLua}

    -- Look & feel: elegant dynamic. Geometry/shadow/blur/motion are owned
    -- here (Nix); border *colors* are owned by DMS matugen at runtime via
    -- ~/.config/hypr/dms/colors.lua (sourced last, wins when present).
    -- Static Nord below is fallback only (first boot before matugen runs).
    hl.config({
        general = {
            gaps_in  = 8,
            gaps_out = 12,
            border_size = 1,
            col = {
                active_border = "rgba(7d7eaaff)",
                inactive_border = "rgba(4c566aaa)",
            },
            resize_on_border = false,
            allow_tearing = false,
            layout = "dwindle",
        },
        decoration = {
            -- 16 matches DMS cornerRadius (seeded in the dms feature module)
            -- so windows and shell popouts share one radius
            rounding       = 16,
            rounding_power = 2,
            active_opacity   = 1.0,
            -- 0.96 keeps unfocused windows distinguishable without the
            -- washed-out gray look stronger dimming produces
            inactive_opacity = 0.96,
            shadow = {
                enabled = true,
                range = 24,
                render_power = 3,
            },
            blur = {
                enabled  = true,
                size     = 10,
                passes   = 2,
                vibrancy = 0.2,
            },
        },
        animations = { enabled = true },
    })

    -- Calmer Fluent-ish motion (matches DMS animationVariant=Fluent):
    -- quick pop-in windows, sliding workspaces, fading layers.
    hl.curve("fluent", { type = "bezier", points = { {0.3, 0.9}, {0.3, 1} } })
    hl.animation({ leaf = "windows",    enabled = true, speed = 5.5, bezier = "fluent", style = "popin 86%" })
    hl.animation({ leaf = "workspaces", enabled = true, speed = 4,   bezier = "fluent", style = "slide" })
    hl.animation({ leaf = "layers",     enabled = true, speed = 5,   bezier = "fluent", style = "fade" })

    -- dwindle.pseudotile no longer exists in the 0.55 Lua config; pseudo is a
    -- per-window toggle via hl.dsp.window.pseudo() now.
    hl.config({
        dwindle = {
            preserve_split = true,
        },
    })

    hl.config({
        misc = {
            force_default_wallpaper = 0,
            disable_hyprland_logo = true,
            disable_splash_rendering = true,
            disable_hyprland_guiutils_check = true,
        },
        xwayland = {
            force_zero_scaling = true,
        },
    })

    hl.config({
        input = {
            kb_layout  = "de,us",
            kb_variant = "nodeadkeys,",
            kb_options = "grp:alt_shift_toggle",
            follow_mouse = 1,
            sensitivity = 0,
            touchpad = { natural_scroll = true },
        },
    })

    -- Keybinds: the DMS-era layout the user asked to keep (2026-09-23),
    -- mapped onto lucid's IPC surface. Everything not bound here lives in
    -- ~/.config/lucid/keybinds.json (workspaces 1-10, arrows/split, mouse,
    -- XF86 media/brightness, screenshots, tap-Super launcher) — loaded by
    -- modules.binds below; edit via Lucid Settings > Keybinds, not here.
    -- Entries the json used to bind were disabled in its seed where they
    -- collided with this set (see home/lucid.nix).
    hl.bind(mainMod .. " + Q", hl.dsp.window.close())
    hl.bind(mainMod .. " + SHIFT + V", hl.dsp.window.float({ action = "toggle" }))
    hl.bind(mainMod .. " + J", hl.dsp.layout("togglesplit"))
    hl.bind(mainMod .. " + left",  hl.dsp.focus({ direction = "left" }))
    hl.bind(mainMod .. " + right", hl.dsp.focus({ direction = "right" }))
    hl.bind(mainMod .. " + up",    hl.dsp.focus({ direction = "up" }))
    hl.bind(mainMod .. " + down",  hl.dsp.focus({ direction = "down" }))

    -- Apps & shell surfaces (lucid IPC equivalents of the old dms-ipc binds)
    hl.bind(mainMod .. " + T",         hl.dsp.exec_cmd(terminal))
    hl.bind(mainMod .. " + SHIFT + E", hl.dsp.exec_cmd(fileManager))
    hl.bind(mainMod .. " + F1",        hl.dsp.exec_cmd(browser))
    hl.bind(mainMod .. " + R",     hl.dsp.exec_cmd("qs ipc call launcher toggle"))
    hl.bind(mainMod .. " + P",     hl.dsp.exec_cmd("qs ipc call launcher power"))
    hl.bind(mainMod .. " + L",     hl.dsp.exec_cmd("qs ipc call lock lock"))
    hl.bind(mainMod .. " + TAB",   hl.dsp.exec_cmd("qs ipc call workspaces toggle"))
    hl.bind(mainMod .. " + V",     hl.dsp.exec_cmd("qs ipc call launcher clipboard"))
    hl.bind(mainMod .. " + N",     hl.dsp.exec_cmd("qs ipc call notifs toggle"))
    hl.bind(mainMod .. " + M",     hl.dsp.exec_cmd("${cfg.terminal} -e btop"))
    hl.bind(mainMod .. " + comma", hl.dsp.exec_cmd("qs ipc call settings toggle"))

    -- Scratchpad ("magic" special workspace, as before lucid)
    hl.bind(mainMod .. " + S",         hl.dsp.workspace.toggle_special("magic"))
    hl.bind(mainMod .. " + SHIFT + S", hl.dsp.window.move({ workspace = "special:magic" }))

    ${lidSwitchLua}

    -- App float rules kept from the ported config (float targets that are
    -- actually installed). The two generic rules this file used to carry
    -- (suppress-maximize-events, fix-xwayland-drags) are NOT duplicated
    -- here: lucid's windowrules module below defines them identically.
    hl.window_rule({ name = "float-file-roller", match = { class = "org.gnome.FileRoller" }, float = true })
    hl.window_rule({ name = "float-loupe",       match = { class = "org.gnome.Loupe" }, float = true })
    -- Firefox Bitwarden popup (German-locale title, as before)
    hl.window_rule({ name = "float-bitwarden-popup", match = { class = "firefox", title = "Erweiterung: .*Bitwarden.*" }, float = true })

    -- Lucid runtime modules (deployed from the lucid flake input by
    -- home/lucid.nix). binds.lua loads ~/.config/lucid/keybinds.json — the
    -- complete bind set (launcher, workspaces, scratchpads, mouse, media
    -- and screenshot keys); windowrules floats lucid surfaces; layerrules
    -- blurs its glass layers (replaces the hand-rolled dms-blur-* rules —
    -- the dms namespaces are gone); glass is the per-app translucency
    -- loader (Settings > Glass writes ~/.config/hypr/lucid-glass.lua).
    -- pcall keeps the compositor alive if a module is mid-sync or missing.
    pcall(require, "modules.json")
    pcall(require, "modules.specials")
    pcall(require, "modules.binds")
    pcall(require, "modules.windowrules")
    pcall(require, "modules.layerrules")
    pcall(require, "modules.glass")

    -- Autostart. Lucid itself starts via the lucid.service user unit,
    -- wanted by graphical-session.target (home/lucid.nix) — upstream's
    -- modules.autostart.lua is deliberately NOT required here (it would
    -- start a second shell next to the service). Cursor theme/size arrive
    -- via the systemd user manager (home/theme.nix) through uwsm — no env
    -- vars needed. Lucid's polkit agent (lucidpolkit) runs inside the
    -- shell, so hyprpolkitagent is no longer autostarted (kept installed
    -- as a manual fallback).
    hl.on("hyprland.start", function()
        -- Clipboard history backend (kept from the DMS setup; lucid's
        -- clipboard launcher reads cliphist too).
        hl.exec_cmd("wl-paste --watch cliphist store")
    end)

    ${cfg.extraConfig}
  '';
in
{
  options.desktop.hyprland = {
    enable = lib.mkEnableOption "Hyprland session config (Lua). Pair with features.desktop-hyprland on the NixOS side";

    terminal = lib.mkOption {
      type = lib.types.str;
      # kitty (single-instance wrap, home/terminal.nix) — ghostty stays
      # installed and keeps lucid's F9 terminal bind.
      default = "kitty";
      description = "Terminal command for the SUPER+T bind";
    };

    fileManager = lib.mkOption {
      type = lib.types.str;
      default = "nautilus";
      description = "File manager for the SUPER+SHIFT+E bind";
    };

    browser = lib.mkOption {
      type = lib.types.str;
      default = "firefox";
      description = "Browser for the SUPER+F1 bind";
    };

    monitors = lib.mkOption {
      type = lib.types.listOf (
        lib.types.submodule {
          options = {
            output = lib.mkOption {
              type = lib.types.str;
              description = "Connector name (e.g. eDP-1); empty string = fallback rule for all monitors";
            };
            mode = lib.mkOption {
              type = lib.types.str;
              default = "preferred";
              description = "Mode, e.g. preferred / 3072x1920@120 / disabled";
            };
            position = lib.mkOption {
              type = lib.types.str;
              default = "auto";
              description = "Position, e.g. auto / 0x0";
            };
            scale = lib.mkOption {
              type = lib.types.str;
              default = "auto";
              description = "Scale, e.g. auto / 2";
            };
          };
        }
      );
      default = [ ];
      description = "Monitors; empty list = Hyprland defaults (preferred mode, auto placement)";
    };

    extraConfig = lib.mkOption {
      type = lib.types.lines;
      default = "";
      description = "Extra Lua appended verbatim to hyprland.lua";
    };
  };

  config = lib.mkIf cfg.enable {
    xdg.configFile = {
      "hypr/hyprland.lua".text = hyprlandLua;

      # Static Nord theme for the DMS shell (bar/launcher/lock), matching the
      # ghostty Nord palette. Optional: dynamic matugen theming is ON by default
      # (features.desktop-hyprland) and overrides the shell theme from the
      # wallpaper — select this file instead if you turn dynamic theming off in
      # DMS Settings: ~/.config/DankMaterialShell/themes/nord/theme.json.
      # Color roles follow DMS's StockThemes schema; the dark/light pair is
      # picked automatically by the shell's color mode.
      "DankMaterialShell/themes/nord/theme.json".text = builtins.toJSON {
        id = "nord";
        dark = {
          name = "Nord";
          primary = "#88C0D0";
          primaryText = "#2E3440";
          primaryContainer = "#5E81AC";
          secondary = "#81A1C1";
          surface = "#2E3440";
          surfaceText = "#ECEFF4";
          surfaceVariant = "#4C566A";
          surfaceVariantText = "#D8DEE9";
          surfaceTint = "#88C0D0";
          background = "#2E3440";
          backgroundText = "#ECEFF4";
          outline = "#4C566A";
          surfaceContainer = "#3B4252";
          surfaceContainerHigh = "#434C5E";
          surfaceContainerHighest = "#4C566A";
        };
        light = {
          name = "Nord";
          primary = "#5E81AC";
          primaryText = "#ECEFF4";
          primaryContainer = "#81A1C1";
          secondary = "#81A1C1";
          surface = "#ECEFF4";
          surfaceText = "#2E3440";
          surfaceVariant = "#D8DEE9";
          surfaceVariantText = "#2E3440";
          surfaceTint = "#5E81AC";
          background = "#ECEFF4";
          backgroundText = "#2E3440";
          outline = "#4C566A";
          surfaceContainer = "#E5E9F0";
          surfaceContainerHigh = "#D8DEE9";
          surfaceContainerHighest = "#D8DEE9";
        };
      };

      # Caelestia-look theme for DMS: the exact palette the Caelestia shell
      # had live on this machine (matugen tonal-spot from its catppuccin/mocha
      # wallpaper — dark values transcribed 1:1 from Caelestia's
      # ~/.local/state/caelestia/scheme.json). The light variant is what
      # Caelestia/matugen derives from the same source color in light mode, so
      # the auto light/dark switch (DMS session themeModeAuto) keeps working.
      # Selected at runtime via the dmsCaelestiaSeed ExecStartPre
      # (modules/features/desktop-hyprland.nix): currentThemeName=custom +
      # this file. DMS regenerates roles we leave out from the theme's primary
      # via matugen, so the subset below is exact where it matters. Turn the
      # clock back to wallpaper-driven colors anytime: DMS Settings → Theme →
      # Dynamic.
      "DankMaterialShell/themes/caelestia/theme.json".text = builtins.toJSON {
        id = "caelestia";
        dark = {
          name = "Caelestia";
          primary = "#C2C1FF";
          primaryText = "#2A2A60";
          primaryContainer = "#7171AC";
          primaryContainerText = "#FFFFFF";
          secondary = "#C6C4E0";
          secondaryText = "#2E2E44";
          secondaryContainer = "#45455C";
          secondaryContainerText = "#B4B2CE";
          tertiary = "#F5B2E0";
          tertiaryText = "#4E1E44";
          tertiaryContainer = "#BB7DA9";
          tertiaryContainerText = "#000000";
          error = "#FFB4AB";
          errorText = "#690005";
          errorContainer = "#93000A";
          errorContainerText = "#FFDAD6";
          surface = "#131317";
          surfaceText = "#E5E1E7";
          surfaceVariant = "#47464F";
          surfaceVariantText = "#C8C5D1";
          surfaceTint = "#C2C1FF";
          background = "#131317";
          backgroundText = "#E5E1E7";
          outline = "#918F9A";
          outlineVariant = "#47464F";
          surfaceContainerLowest = "#0E0E12";
          surfaceContainerLow = "#1C1B1F";
          surfaceContainer = "#201F23";
          surfaceContainerHigh = "#2A292E";
          surfaceContainerHighest = "#353438";
          surfaceBright = "#39393D";
          surfaceDim = "#131317";
          inverseSurface = "#E5E1E7";
          inverseOnSurface = "#313034";
          inversePrimary = "#595992";
          scrim = "#000000";
          shadow = "#000000";
          primaryFixed = "#E2DFFF";
          primaryFixedDim = "#C2C1FF";
          onPrimaryFixed = "#14134A";
          onPrimaryFixedVariant = "#414178";
          secondaryFixed = "#E2E0FD";
          secondaryFixedDim = "#C6C4E0";
          onSecondaryFixed = "#19192E";
          onSecondaryFixedVariant = "#45455C";
          tertiaryFixed = "#FFD7F0";
          tertiaryFixedDim = "#F5B2E0";
          onTertiaryFixed = "#35082E";
          onTertiaryFixedVariant = "#68355C";
        };
        light = {
          name = "Caelestia";
          primary = "#595992";
          primaryText = "#FFFFFF";
          primaryContainer = "#E2DFFF";
          primaryContainerText = "#14134A";
          secondary = "#5D5C72";
          secondaryText = "#FFFFFF";
          secondaryContainer = "#E2E0F9";
          secondaryContainerText = "#1A1A2C";
          tertiary = "#795369";
          tertiaryText = "#FFFFFF";
          tertiaryContainer = "#FFD8EB";
          tertiaryContainerText = "#2F1124";
          error = "#BA1A1A";
          errorText = "#FFFFFF";
          errorContainer = "#FFDAD6";
          errorContainerText = "#410002";
          surface = "#FCF8FF";
          surfaceText = "#1B1B21";
          surfaceVariant = "#E4E1EC";
          surfaceVariantText = "#47464F";
          surfaceTint = "#595992";
          background = "#FCF8FF";
          backgroundText = "#1B1B21";
          outline = "#777680";
          outlineVariant = "#C8C5D0";
          surfaceContainerLowest = "#FFFFFF";
          surfaceContainerLow = "#F6F2FA";
          surfaceContainer = "#F0ECF4";
          surfaceContainerHigh = "#EAE7EF";
          surfaceContainerHighest = "#E4E1E9";
          surfaceBright = "#FCF8FF";
          surfaceDim = "#DCD9E0";
          inverseSurface = "#303036";
          inverseOnSurface = "#F3EFF7";
          inversePrimary = "#C2C1FF";
          scrim = "#000000";
          shadow = "#000000";
          primaryFixed = "#E2DFFF";
          primaryFixedDim = "#C2C1FF";
          onPrimaryFixed = "#14134A";
          onPrimaryFixedVariant = "#414178";
          secondaryFixed = "#E2E0F9";
          secondaryFixedDim = "#C6C4DD";
          onSecondaryFixed = "#1A1A2C";
          onSecondaryFixedVariant = "#454559";
          tertiaryFixed = "#FFD8EB";
          tertiaryFixedDim = "#E9B9D2";
          onTertiaryFixed = "#2F1124";
          onTertiaryFixedVariant = "#5F3C51";
        };
      };
    };
  };
}
