{
  config,
  lib,
  pkgs,
  ...
}:

let
  cfg = config.desktop.hyprland;

  # Hyprland 0.55+ Lua config. Ported from the old hyprlang dots
  # (~/Downloads/dots-main/hypr/hyprland.conf); DankMaterialShell replaces
  # waybar, rofi, dunst, hyprpaper, hyprlock and hypridle from that setup.
  monitorLua = m: ''
    hl.monitor({
        output   = "${m.output}",
        mode     = "${m.mode}",
        position = "${m.position}",
        scale    = "${m.scale}",
    })
  '';

  monitorsLua =
    if cfg.monitors == [ ] then
      monitorLua {
        output = "";
        mode = "preferred";
        position = "auto";
        scale = "auto";
      }
    else
      lib.concatMapStrings monitorLua cfg.monitors;

  # Lid switch: internal panel off when closed, configured mode restored when
  # opened (docked use; logind still suspends per the laptop profile).
  lidSwitchLua =
    if cfg.monitors == [ ] then
      ""
    else
      let
        m = builtins.head cfg.monitors;
      in
      ''
        hl.bind("switch:on:Lid Switch", hl.dsp.exec_cmd("hyprctl keyword monitor \"${m.output}, disable\""), { locked = true })
        hl.bind("switch:off:Lid Switch", hl.dsp.exec_cmd("hyprctl keyword monitor \"${m.output}, ${m.mode}, ${m.position}, ${m.scale}\""), { locked = true })
      '';

  hyprlandLua = ''
    -- Generated by home-manager from home/hyprland.nix — do not edit.
    -- API reference: hyprland 0.55 Lua config (share/hypr/hyprland.lua in the
    -- hyprland package, wiki.hypr.land Configuring section).

    local terminal    = "${cfg.terminal}"
    local fileManager = "${cfg.fileManager}"
    local browser     = "${cfg.browser}"
    local mainMod     = "SUPER"

    -- Monitors
    ${monitorsLua}

    -- Look & feel (from the old config)
    hl.config({
        general = {
            gaps_in  = 5,
            gaps_out = 5,
            border_size = 1,
            col = {
                -- Nord frost gradient (was teal/green in the old config)
                active_border = { colors = { "rgba(81a1c1ff)", "rgba(88c0d0ff)" }, angle = 45 },
                inactive_border = "rgba(4c566aaa)",
            },
            resize_on_border = false,
            allow_tearing = false,
            layout = "dwindle",
        },
        decoration = {
            rounding       = 8,
            rounding_power = 2,
            active_opacity   = 0.99,
            inactive_opacity = 0.90,
            shadow = {
                enabled = true,
                range = 4,
                render_power = 3,
            },
            blur = {
                enabled  = true,
                size     = 3,
                passes   = 1,
                vibrancy = 0.1696,
            },
        },
        animations = { enabled = true },
    })

    -- dwindle.pseudotile no longer exists in the 0.55 Lua config; pseudo is a
    -- per-window toggle via hl.dsp.window.pseudo() now.
    hl.config({
        dwindle = {
            preserve_split = true,
        },
    })

    hl.config({
        misc = {
            force_default_wallpaper = 0,
            disable_hyprland_logo = true,
            disable_splash_rendering = true,
            disable_hyprland_guiutils_check = true,
        },
        xwayland = {
            force_zero_scaling = true,
        },
    })

    hl.config({
        input = {
            kb_layout  = "de,us",
            kb_variant = "nodeadkeys,",
            kb_options = "grp:alt_shift_toggle",
            follow_mouse = 1,
            sensitivity = 0,
            touchpad = { natural_scroll = true },
        },
    })

    -- Window management
    hl.bind(mainMod .. " + Q", hl.dsp.window.close())
    hl.bind(mainMod .. " + SHIFT + V", hl.dsp.window.float({ action = "toggle" }))
    hl.bind(mainMod .. " + J", hl.dsp.layout("togglesplit"))
    hl.bind(mainMod .. " + left",  hl.dsp.focus({ direction = "left" }))
    hl.bind(mainMod .. " + right", hl.dsp.focus({ direction = "right" }))
    hl.bind(mainMod .. " + up",    hl.dsp.focus({ direction = "up" }))
    hl.bind(mainMod .. " + down",  hl.dsp.focus({ direction = "down" }))

    -- Apps: DMS owns launcher (SUPER+R), power menu incl. suspend/logout
    -- (SUPER+P), lock (SUPER+L — GNOME style)
    hl.bind(mainMod .. " + T",         hl.dsp.exec_cmd(terminal))
    hl.bind(mainMod .. " + SHIFT + E", hl.dsp.exec_cmd(fileManager))
    hl.bind(mainMod .. " + F1",        hl.dsp.exec_cmd(browser))
    hl.bind(mainMod .. " + R",   hl.dsp.exec_cmd("dms ipc call spotlight toggle"))
    hl.bind(mainMod .. " + P",   hl.dsp.exec_cmd("dms ipc call powermenu toggle"))
    hl.bind(mainMod .. " + L",   hl.dsp.exec_cmd("dms ipc call lock lock"))
    hl.bind(mainMod .. " + TAB", hl.dsp.exec_cmd("dms ipc call hypr toggleOverview"))

    -- DMS surfaces. Old-config binds kept; new ones follow GNOME where a
    -- default exists (SUPER+V clipboard like GNOME 48+, SUPER+N
    -- notifications) and DMS's own conventions otherwise. SUPER+M used to
    -- exit Hyprland raw — dropped as a footgun, the power menu logs out.
    hl.bind(mainMod .. " + V",      hl.dsp.exec_cmd("dms ipc call clipboard toggle"))
    hl.bind(mainMod .. " + N",      hl.dsp.exec_cmd("dms ipc call notifications toggle"))
    hl.bind(mainMod .. " + M",      hl.dsp.exec_cmd("dms ipc call processlist focusOrToggle"))
    hl.bind(mainMod .. " + comma",  hl.dsp.exec_cmd("dms ipc call settings focusOrToggle"))
    hl.bind(mainMod .. " + C",      hl.dsp.exec_cmd("dms ipc call control-center toggle"))
    hl.bind(mainMod .. " + slash",  hl.dsp.exec_cmd("dms ipc call keybinds open"))

    -- Workspaces 1..10 (10th on key 0), move with SHIFT
    for i = 1, 10 do
        local key = i % 10
        hl.bind(mainMod .. " + " .. key,         hl.dsp.focus({ workspace = i }))
        hl.bind(mainMod .. " + SHIFT + " .. key, hl.dsp.window.move({ workspace = i }))
    end

    -- Scratchpad ("magic" special workspace)
    hl.bind(mainMod .. " + S",         hl.dsp.workspace.toggle_special("magic"))
    hl.bind(mainMod .. " + SHIFT + S", hl.dsp.window.move({ workspace = "special:magic" }))

    -- Scroll through workspaces; move/resize with the mouse
    hl.bind(mainMod .. " + mouse_down", hl.dsp.focus({ workspace = "e+1" }))
    hl.bind(mainMod .. " + mouse_up",   hl.dsp.focus({ workspace = "e-1" }))
    hl.bind(mainMod .. " + mouse:272", hl.dsp.window.drag(),   { mouse = true })
    hl.bind(mainMod .. " + mouse:273", hl.dsp.window.resize(), { mouse = true })

    -- Media keys via DMS (shows its OSD): volume, mic, brightness, MPRIS
    hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("dms ipc call audio increment 5"), { locked = true, repeating = true })
    hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("dms ipc call audio decrement 5"), { locked = true, repeating = true })
    hl.bind("XF86AudioMute",        hl.dsp.exec_cmd("dms ipc call audio mute"), { locked = true })
    hl.bind("XF86AudioMicMute",     hl.dsp.exec_cmd("dms ipc call mic mute"), { locked = true })
    hl.bind("XF86MonBrightnessUp",   hl.dsp.exec_cmd("dms ipc call brightness increment 5 \"\""), { locked = true, repeating = true })
    hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("dms ipc call brightness decrement 5 \"\""), { locked = true, repeating = true })
    hl.bind("XF86AudioNext",  hl.dsp.exec_cmd("dms ipc call mpris next"), { locked = true })
    hl.bind("XF86AudioPrev",  hl.dsp.exec_cmd("dms ipc call mpris previous"), { locked = true })
    hl.bind("XF86AudioPlay",  hl.dsp.exec_cmd("dms ipc call mpris playPause"), { locked = true })
    hl.bind("XF86AudioPause", hl.dsp.exec_cmd("dms ipc call mpris playPause"), { locked = true })

    -- Screenshots (DMS CLI: saves file + clipboard)
    hl.bind("Print",               hl.dsp.exec_cmd("dms screenshot"),       { description = "Screenshot: region" })
    hl.bind(mainMod .. " + Print", hl.dsp.exec_cmd("dms screenshot full"),  { description = "Screenshot: focused output" })

    ${lidSwitchLua}

    -- Window rules (ported; float targets that are actually installed)
    hl.window_rule({
        name  = "suppress-maximize-events",
        match = { class = ".*" },
        suppress_event = "maximize",
    })
    hl.window_rule({
        name  = "fix-xwayland-drags",
        match = { class = "^$", title = "^$", xwayland = true, float = true, fullscreen = false, pin = false },
        no_focus = true,
    })
    hl.window_rule({ name = "float-file-roller", match = { class = "org.gnome.FileRoller" }, float = true })
    hl.window_rule({ name = "float-loupe",       match = { class = "org.gnome.Loupe" }, float = true })
    -- Firefox Bitwarden popup (German-locale title, as before)
    hl.window_rule({ name = "float-bitwarden-popup", match = { class = "firefox", title = "Erweiterung: .*Bitwarden.*" }, float = true })

    -- Autostart. DMS itself starts via the dms.service user unit, wanted by
    -- wayland-session@hyprland.desktop.target (modules/features/desktop-hyprland.nix),
    -- so it only runs in Hyprland sessions. Cursor theme/size arrive via the
    -- systemd user manager (home/theme.nix) through uwsm — no env vars needed.
    hl.on("hyprland.start", function()
        -- Polkit authentication agent (GNOME Shell is not running here)
        hl.exec_cmd("${pkgs.hyprpolkitagent}/bin/hyprpolkitagent")
        -- Clipboard history backend for the DMS clipboard modal (DMS
        -- Compositor Setup docs). Harmless if DMS tracks clips itself.
        hl.exec_cmd("wl-paste --watch cliphist store")
    end)

    ${cfg.extraConfig}
  '';
in
{
  options.desktop.hyprland = {
    enable = lib.mkEnableOption "Hyprland session config (Lua). Pair with features.desktop-hyprland on the NixOS side";

    terminal = lib.mkOption {
      type = lib.types.str;
      default = "ghostty";
      description = "Terminal command for the SUPER+T bind";
    };

    fileManager = lib.mkOption {
      type = lib.types.str;
      default = "nautilus";
      description = "File manager for the SUPER+SHIFT+E bind";
    };

    browser = lib.mkOption {
      type = lib.types.str;
      default = "firefox";
      description = "Browser for the SUPER+F1 bind";
    };

    monitors = lib.mkOption {
      type = lib.types.listOf (
        lib.types.submodule {
          options = {
            output = lib.mkOption {
              type = lib.types.str;
              description = "Connector name (e.g. eDP-1); empty string = fallback rule for all monitors";
            };
            mode = lib.mkOption {
              type = lib.types.str;
              default = "preferred";
              description = "Mode, e.g. preferred / 3072x1920@120 / disabled";
            };
            position = lib.mkOption {
              type = lib.types.str;
              default = "auto";
              description = "Position, e.g. auto / 0x0";
            };
            scale = lib.mkOption {
              type = lib.types.str;
              default = "auto";
              description = "Scale, e.g. auto / 2";
            };
          };
        }
      );
      default = [ ];
      description = "Monitors; empty list = Hyprland defaults (preferred mode, auto placement)";
    };

    extraConfig = lib.mkOption {
      type = lib.types.lines;
      default = "";
      description = "Extra Lua appended verbatim to hyprland.lua";
    };
  };

  config = lib.mkIf cfg.enable {
    xdg.configFile."hypr/hyprland.lua".text = hyprlandLua;

    # Static Nord theme for the DMS shell (bar/launcher/lock), matching the
    # ghostty Nord palette. Optional: dynamic matugen theming is ON by default
    # (features.desktop-hyprland) and overrides the shell theme from the
    # wallpaper — select this file instead if you turn dynamic theming off in
    # DMS Settings: ~/.config/DankMaterialShell/themes/nord/theme.json.
    # Color roles follow DMS's StockThemes schema; the dark/light pair is
    # picked automatically by the shell's color mode.
    xdg.configFile."DankMaterialShell/themes/nord/theme.json".text = builtins.toJSON {
      id = "nord";
      dark = {
        name = "Nord";
        primary = "#88C0D0";
        primaryText = "#2E3440";
        primaryContainer = "#5E81AC";
        secondary = "#81A1C1";
        surface = "#2E3440";
        surfaceText = "#ECEFF4";
        surfaceVariant = "#4C566A";
        surfaceVariantText = "#D8DEE9";
        surfaceTint = "#88C0D0";
        background = "#2E3440";
        backgroundText = "#ECEFF4";
        outline = "#4C566A";
        surfaceContainer = "#3B4252";
        surfaceContainerHigh = "#434C5E";
        surfaceContainerHighest = "#4C566A";
      };
      light = {
        name = "Nord";
        primary = "#5E81AC";
        primaryText = "#ECEFF4";
        primaryContainer = "#81A1C1";
        secondary = "#81A1C1";
        surface = "#ECEFF4";
        surfaceText = "#2E3440";
        surfaceVariant = "#D8DEE9";
        surfaceVariantText = "#2E3440";
        surfaceTint = "#5E81AC";
        background = "#ECEFF4";
        backgroundText = "#2E3440";
        outline = "#4C566A";
        surfaceContainer = "#E5E9F0";
        surfaceContainerHigh = "#D8DEE9";
        surfaceContainerHighest = "#D8DEE9";
      };
    };
  };
}
