{
  config,
  lib,
  pkgs,
  ...
}:

let
  cfg = config.desktop.hyprland;

  # Hyprland 0.55+ Lua config. Ported from the old hyprlang dots
  # (~/Downloads/dots-main/hypr/hyprland.conf); DankMaterialShell replaces
  # waybar, rofi, dunst, hyprpaper, hyprlock and hypridle from that setup.
  monitorLua = m: ''
    hl.monitor({
        output   = "${m.output}",
        mode     = "${m.mode}",
        position = "${m.position}",
        scale    = "${m.scale}",
    })
  '';

  monitorsLua =
    if cfg.monitors == [ ] then
      monitorLua {
        output = "";
        mode = "preferred";
        position = "auto";
        scale = "auto";
      }
    else
      lib.concatMapStrings monitorLua cfg.monitors;

  # Lid switch: internal panel off when closed, configured mode restored when
  # opened (docked use; logind still suspends per the laptop profile).
  lidSwitchLua =
    if cfg.monitors == [ ] then
      ""
    else
      let
        m = builtins.head cfg.monitors;
      in
      ''
        hl.bind("switch:on:Lid Switch", hl.dsp.exec_cmd("hyprctl keyword monitor \"${m.output}, disable\""), { locked = true })
        hl.bind("switch:off:Lid Switch", hl.dsp.exec_cmd("hyprctl keyword monitor \"${m.output}, ${m.mode}, ${m.position}, ${m.scale}\""), { locked = true })
      '';

  hyprlandLua = ''
    -- Generated by home-manager from home/hyprland.nix — do not edit.
    -- API reference: hyprland 0.55 Lua config (share/hypr/hyprland.lua in the
    -- hyprland package, wiki.hypr.land Configuring section).

    local terminal    = "${cfg.terminal}"
    local fileManager = "${cfg.fileManager}"
    local browser     = "${cfg.browser}"
    local mainMod     = "SUPER"

    -- Monitors
    ${monitorsLua}

    -- Look & feel (from the old config)
    hl.config({
        general = {
            gaps_in  = 5,
            gaps_out = 5,
            border_size = 1,
            col = {
                -- Nord frost gradient (was teal/green in the old config)
                active_border = { colors = { "rgba(81a1c1ff)", "rgba(88c0d0ff)" }, angle = 45 },
                inactive_border = "rgba(4c566aaa)",
            },
            resize_on_border = false,
            allow_tearing = false,
            layout = "dwindle",
        },
        decoration = {
            rounding       = 8,
            rounding_power = 2,
            active_opacity   = 0.99,
            inactive_opacity = 0.90,
            shadow = {
                enabled = true,
                range = 4,
                render_power = 3,
            },
            blur = {
                enabled  = true,
                size     = 3,
                passes   = 1,
                vibrancy = 0.1696,
            },
        },
        animations = { enabled = true },
    })

    -- dwindle.pseudotile no longer exists in the 0.55 Lua config; pseudo is a
    -- per-window toggle via hl.dsp.window.pseudo() now.
    hl.config({
        dwindle = {
            preserve_split = true,
        },
    })

    hl.config({
        misc = {
            force_default_wallpaper = 0,
            disable_hyprland_logo = true,
            disable_splash_rendering = true,
            disable_hyprland_guiutils_check = true,
        },
        xwayland = {
            force_zero_scaling = true,
        },
    })

    hl.config({
        input = {
            kb_layout  = "de,us",
            kb_variant = "nodeadkeys,",
            kb_options = "grp:alt_shift_toggle",
            follow_mouse = 1,
            sensitivity = 0,
            touchpad = { natural_scroll = true },
        },
    })

    -- Window management
    hl.bind(mainMod .. " + Q", hl.dsp.window.close())
    hl.bind(mainMod .. " + SHIFT + V", hl.dsp.window.float({ action = "toggle" }))
    hl.bind(mainMod .. " + J", hl.dsp.layout("togglesplit"))
    hl.bind(mainMod .. " + left",  hl.dsp.focus({ direction = "left" }))
    hl.bind(mainMod .. " + right", hl.dsp.focus({ direction = "right" }))
    hl.bind(mainMod .. " + up",    hl.dsp.focus({ direction = "up" }))
    hl.bind(mainMod .. " + down",  hl.dsp.focus({ direction = "down" }))

    -- Apps: DMS owns launcher (SUPER+R), power menu incl. suspend/logout
    -- (SUPER+P), lock (SUPER+L — GNOME style)
    hl.bind(mainMod .. " + T",         hl.dsp.exec_cmd(terminal))
    hl.bind(mainMod .. " + SHIFT + E", hl.dsp.exec_cmd(fileManager))
    hl.bind(mainMod .. " + F1",        hl.dsp.exec_cmd(browser))
    hl.bind(mainMod .. " + R",   hl.dsp.exec_cmd("dms ipc call spotlight toggle"))
    hl.bind(mainMod .. " + P",   hl.dsp.exec_cmd("dms ipc call powermenu toggle"))
    hl.bind(mainMod .. " + L",   hl.dsp.exec_cmd("dms ipc call lock lock"))
    hl.bind(mainMod .. " + TAB", hl.dsp.exec_cmd("dms ipc call hypr toggleOverview"))

    -- DMS surfaces. Old-config binds kept; new ones follow GNOME where a
    -- default exists (SUPER+V clipboard like GNOME 48+, SUPER+N
    -- notifications) and DMS's own conventions otherwise. SUPER+M used to
    -- exit Hyprland raw — dropped as a footgun, the power menu logs out.
    hl.bind(mainMod .. " + V",      hl.dsp.exec_cmd("dms ipc call clipboard toggle"))
    hl.bind(mainMod .. " + N",      hl.dsp.exec_cmd("dms ipc call notifications toggle"))
    hl.bind(mainMod .. " + M",      hl.dsp.exec_cmd("dms ipc call processlist focusOrToggle"))
    hl.bind(mainMod .. " + comma",  hl.dsp.exec_cmd("dms ipc call settings focusOrToggle"))
    hl.bind(mainMod .. " + C",      hl.dsp.exec_cmd("dms ipc call control-center toggle"))
    hl.bind(mainMod .. " + slash",  hl.dsp.exec_cmd("dms ipc call keybinds open"))

    -- Workspaces 1..10 (10th on key 0), move with SHIFT
    for i = 1, 10 do
        local key = i % 10
        hl.bind(mainMod .. " + " .. key,         hl.dsp.focus({ workspace = i }))
        hl.bind(mainMod .. " + SHIFT + " .. key, hl.dsp.window.move({ workspace = i }))
    end

    -- Scratchpad ("magic" special workspace)
    hl.bind(mainMod .. " + S",         hl.dsp.workspace.toggle_special("magic"))
    hl.bind(mainMod .. " + SHIFT + S", hl.dsp.window.move({ workspace = "special:magic" }))

    -- Scroll through workspaces; move/resize with the mouse
    hl.bind(mainMod .. " + mouse_down", hl.dsp.focus({ workspace = "e+1" }))
    hl.bind(mainMod .. " + mouse_up",   hl.dsp.focus({ workspace = "e-1" }))
    hl.bind(mainMod .. " + mouse:272", hl.dsp.window.drag(),   { mouse = true })
    hl.bind(mainMod .. " + mouse:273", hl.dsp.window.resize(), { mouse = true })

    -- Media keys via DMS (shows its OSD): volume, mic, brightness, MPRIS
    hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("dms ipc call audio increment 5"), { locked = true, repeating = true })
    hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("dms ipc call audio decrement 5"), { locked = true, repeating = true })
    hl.bind("XF86AudioMute",        hl.dsp.exec_cmd("dms ipc call audio mute"), { locked = true })
    hl.bind("XF86AudioMicMute",     hl.dsp.exec_cmd("dms ipc call mic mute"), { locked = true })
    hl.bind("XF86MonBrightnessUp",   hl.dsp.exec_cmd("dms ipc call brightness increment 5 \"\""), { locked = true, repeating = true })
    hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("dms ipc call brightness decrement 5 \"\""), { locked = true, repeating = true })
    hl.bind("XF86AudioNext",  hl.dsp.exec_cmd("dms ipc call mpris next"), { locked = true })
    hl.bind("XF86AudioPrev",  hl.dsp.exec_cmd("dms ipc call mpris previous"), { locked = true })
    hl.bind("XF86AudioPlay",  hl.dsp.exec_cmd("dms ipc call mpris playPause"), { locked = true })
    hl.bind("XF86AudioPause", hl.dsp.exec_cmd("dms ipc call mpris playPause"), { locked = true })

    -- Screenshots (DMS CLI: saves file + clipboard)
    hl.bind("Print",               hl.dsp.exec_cmd("dms screenshot"),       { description = "Screenshot: region" })
    hl.bind(mainMod .. " + Print", hl.dsp.exec_cmd("dms screenshot full"),  { description = "Screenshot: focused output" })

    ${lidSwitchLua}

    -- Window rules (ported; float targets that are actually installed)
    hl.window_rule({
        name  = "suppress-maximize-events",
        match = { class = ".*" },
        suppress_event = "maximize",
    })
    hl.window_rule({
        name  = "fix-xwayland-drags",
        match = { class = "^$", title = "^$", xwayland = true, float = true, fullscreen = false, pin = false },
        no_focus = true,
    })
    hl.window_rule({ name = "float-file-roller", match = { class = "org.gnome.FileRoller" }, float = true })
    hl.window_rule({ name = "float-loupe",       match = { class = "org.gnome.Loupe" }, float = true })
    -- Firefox Bitwarden popup (German-locale title, as before)
    hl.window_rule({ name = "float-bitwarden-popup", match = { class = "firefox", title = "Erweiterung: .*Bitwarden.*" }, float = true })

    -- DMS surface blur. Hyprland lacks ext-bg-effect-v1, so DMS cannot blur
    -- itself — dms doctor keeps reporting blur "unsupported" (expected);
    -- compositor-side layer rules do the job instead (DMS "Layer Namespaces"
    -- docs). Visibility needs transparent surfaces: lower Surface Opacity in
    -- DMS Settings → Theme & Colors.
    hl.layer_rule({
        name = "dms-blur-modals",
        match = { namespace = "dms:(color-picker|clipboard|spotlight|settings|polkit|power-menu|notification-center-modal|workspace-overview|process-list-modal|hyprkeybinds|file-browser|bluetooth-pairing|network-info|network-info-wired|wifi-password|confirm-modal|modal)" },
        blur = true,
        ignore_alpha = 0,
    })
    hl.layer_rule({
        name = "dms-blur-shell",
        match = { namespace = "dms:(bar|control-center|dash|battery|app-launcher|popout|notification-center-popout|process-list-popout|tooltip|toast|tray-menu-window|osd|dock|slideout)|dock-context-menu" },
        blur = true,
        ignore_alpha = 0,
    })

    -- Autostart. DMS itself starts via the dms.service user unit, wanted by
    -- graphical-session.target (modules/features/desktop-hyprland.nix), so it
    -- only runs in graphical sessions. Cursor theme/size arrive via the
    -- systemd user manager (home/theme.nix) through uwsm — no env vars needed.
    hl.on("hyprland.start", function()
        -- Polkit authentication agent (GNOME Shell is not running here)
        hl.exec_cmd("${pkgs.hyprpolkitagent}/bin/hyprpolkitagent")
        -- Clipboard history backend for the DMS clipboard modal (DMS
        -- Compositor Setup docs). Harmless if DMS tracks clips itself.
        hl.exec_cmd("wl-paste --watch cliphist store")
    end)

    ${cfg.extraConfig}
  '';
in
{
  options.desktop.hyprland = {
    enable = lib.mkEnableOption "Hyprland session config (Lua). Pair with features.desktop-hyprland on the NixOS side";

    terminal = lib.mkOption {
      type = lib.types.str;
      default = "ghostty";
      description = "Terminal command for the SUPER+T bind";
    };

    fileManager = lib.mkOption {
      type = lib.types.str;
      default = "nautilus";
      description = "File manager for the SUPER+SHIFT+E bind";
    };

    browser = lib.mkOption {
      type = lib.types.str;
      default = "firefox";
      description = "Browser for the SUPER+F1 bind";
    };

    monitors = lib.mkOption {
      type = lib.types.listOf (
        lib.types.submodule {
          options = {
            output = lib.mkOption {
              type = lib.types.str;
              description = "Connector name (e.g. eDP-1); empty string = fallback rule for all monitors";
            };
            mode = lib.mkOption {
              type = lib.types.str;
              default = "preferred";
              description = "Mode, e.g. preferred / 3072x1920@120 / disabled";
            };
            position = lib.mkOption {
              type = lib.types.str;
              default = "auto";
              description = "Position, e.g. auto / 0x0";
            };
            scale = lib.mkOption {
              type = lib.types.str;
              default = "auto";
              description = "Scale, e.g. auto / 2";
            };
          };
        }
      );
      default = [ ];
      description = "Monitors; empty list = Hyprland defaults (preferred mode, auto placement)";
    };

    extraConfig = lib.mkOption {
      type = lib.types.lines;
      default = "";
      description = "Extra Lua appended verbatim to hyprland.lua";
    };
  };

  config = lib.mkIf cfg.enable {
    xdg.configFile = {
      "hypr/hyprland.lua".text = hyprlandLua;

      # Static Nord theme for the DMS shell (bar/launcher/lock), matching the
      # ghostty Nord palette. Optional: dynamic matugen theming is ON by default
      # (features.desktop-hyprland) and overrides the shell theme from the
      # wallpaper — select this file instead if you turn dynamic theming off in
      # DMS Settings: ~/.config/DankMaterialShell/themes/nord/theme.json.
      # Color roles follow DMS's StockThemes schema; the dark/light pair is
      # picked automatically by the shell's color mode.
      "DankMaterialShell/themes/nord/theme.json".text = builtins.toJSON {
        id = "nord";
        dark = {
          name = "Nord";
          primary = "#88C0D0";
          primaryText = "#2E3440";
          primaryContainer = "#5E81AC";
          secondary = "#81A1C1";
          surface = "#2E3440";
          surfaceText = "#ECEFF4";
          surfaceVariant = "#4C566A";
          surfaceVariantText = "#D8DEE9";
          surfaceTint = "#88C0D0";
          background = "#2E3440";
          backgroundText = "#ECEFF4";
          outline = "#4C566A";
          surfaceContainer = "#3B4252";
          surfaceContainerHigh = "#434C5E";
          surfaceContainerHighest = "#4C566A";
        };
        light = {
          name = "Nord";
          primary = "#5E81AC";
          primaryText = "#ECEFF4";
          primaryContainer = "#81A1C1";
          secondary = "#81A1C1";
          surface = "#ECEFF4";
          surfaceText = "#2E3440";
          surfaceVariant = "#D8DEE9";
          surfaceVariantText = "#2E3440";
          surfaceTint = "#5E81AC";
          background = "#ECEFF4";
          backgroundText = "#2E3440";
          outline = "#4C566A";
          surfaceContainer = "#E5E9F0";
          surfaceContainerHigh = "#D8DEE9";
          surfaceContainerHighest = "#D8DEE9";
        };
      };

      # Caelestia-look theme for DMS: the exact palette the Caelestia shell
      # had live on this machine (matugen tonal-spot from its catppuccin/mocha
      # wallpaper — dark values transcribed 1:1 from Caelestia's
      # ~/.local/state/caelestia/scheme.json). The light variant is what
      # Caelestia/matugen derives from the same source color in light mode, so
      # the auto light/dark switch (DMS session themeModeAuto) keeps working.
      # Selected at runtime via the dmsCaelestiaSeed ExecStartPre
      # (modules/features/desktop-hyprland.nix): currentThemeName=custom +
      # this file. DMS regenerates roles we leave out from the theme's primary
      # via matugen, so the subset below is exact where it matters. Turn the
      # clock back to wallpaper-driven colors anytime: DMS Settings → Theme →
      # Dynamic.
      "DankMaterialShell/themes/caelestia/theme.json".text = builtins.toJSON {
        id = "caelestia";
        dark = {
          name = "Caelestia";
          primary = "#C2C1FF";
          primaryText = "#2A2A60";
          primaryContainer = "#7171AC";
          primaryContainerText = "#FFFFFF";
          secondary = "#C6C4E0";
          secondaryText = "#2E2E44";
          secondaryContainer = "#45455C";
          secondaryContainerText = "#B4B2CE";
          tertiary = "#F5B2E0";
          tertiaryText = "#4E1E44";
          tertiaryContainer = "#BB7DA9";
          tertiaryContainerText = "#000000";
          error = "#FFB4AB";
          errorText = "#690005";
          errorContainer = "#93000A";
          errorContainerText = "#FFDAD6";
          surface = "#131317";
          surfaceText = "#E5E1E7";
          surfaceVariant = "#47464F";
          surfaceVariantText = "#C8C5D1";
          surfaceTint = "#C2C1FF";
          background = "#131317";
          backgroundText = "#E5E1E7";
          outline = "#918F9A";
          outlineVariant = "#47464F";
          surfaceContainerLowest = "#0E0E12";
          surfaceContainerLow = "#1C1B1F";
          surfaceContainer = "#201F23";
          surfaceContainerHigh = "#2A292E";
          surfaceContainerHighest = "#353438";
          surfaceBright = "#39393D";
          surfaceDim = "#131317";
          inverseSurface = "#E5E1E7";
          inverseOnSurface = "#313034";
          inversePrimary = "#595992";
          scrim = "#000000";
          shadow = "#000000";
          primaryFixed = "#E2DFFF";
          primaryFixedDim = "#C2C1FF";
          onPrimaryFixed = "#14134A";
          onPrimaryFixedVariant = "#414178";
          secondaryFixed = "#E2E0FD";
          secondaryFixedDim = "#C6C4E0";
          onSecondaryFixed = "#19192E";
          onSecondaryFixedVariant = "#45455C";
          tertiaryFixed = "#FFD7F0";
          tertiaryFixedDim = "#F5B2E0";
          onTertiaryFixed = "#35082E";
          onTertiaryFixedVariant = "#68355C";
        };
        light = {
          name = "Caelestia";
          primary = "#595992";
          primaryText = "#FFFFFF";
          primaryContainer = "#E2DFFF";
          primaryContainerText = "#14134A";
          secondary = "#5D5C72";
          secondaryText = "#FFFFFF";
          secondaryContainer = "#E2E0F9";
          secondaryContainerText = "#1A1A2C";
          tertiary = "#795369";
          tertiaryText = "#FFFFFF";
          tertiaryContainer = "#FFD8EB";
          tertiaryContainerText = "#2F1124";
          error = "#BA1A1A";
          errorText = "#FFFFFF";
          errorContainer = "#FFDAD6";
          errorContainerText = "#410002";
          surface = "#FCF8FF";
          surfaceText = "#1B1B21";
          surfaceVariant = "#E4E1EC";
          surfaceVariantText = "#47464F";
          surfaceTint = "#595992";
          background = "#FCF8FF";
          backgroundText = "#1B1B21";
          outline = "#777680";
          outlineVariant = "#C8C5D0";
          surfaceContainerLowest = "#FFFFFF";
          surfaceContainerLow = "#F6F2FA";
          surfaceContainer = "#F0ECF4";
          surfaceContainerHigh = "#EAE7EF";
          surfaceContainerHighest = "#E4E1E9";
          surfaceBright = "#FCF8FF";
          surfaceDim = "#DCD9E0";
          inverseSurface = "#303036";
          inverseOnSurface = "#F3EFF7";
          inversePrimary = "#C2C1FF";
          scrim = "#000000";
          shadow = "#000000";
          primaryFixed = "#E2DFFF";
          primaryFixedDim = "#C2C1FF";
          onPrimaryFixed = "#14134A";
          onPrimaryFixedVariant = "#414178";
          secondaryFixed = "#E2E0F9";
          secondaryFixedDim = "#C6C4DD";
          onSecondaryFixed = "#1A1A2C";
          onSecondaryFixedVariant = "#454559";
          tertiaryFixed = "#FFD8EB";
          tertiaryFixedDim = "#E9B9D2";
          onTertiaryFixed = "#2F1124";
          onTertiaryFixedVariant = "#5F3C51";
        };
      };
    };
  };
}
