{
  imports = [
    ./bluetooth.nix
    ./desktop-gnome.nix
    ./filesystem.nix
    ./fonts.nix
    ./impermanence.nix
    ./kernel.nix
    ./nas.nix
    ./network-optimization.nix
    ./onlyoffice.nix
    ./oomd.nix
    ./power-tlp.nix
    ./virtualization.nix
    ./secureboot.nix
    ./sops.nix
    ./vpn.nix
    ./zram.nix
  ];
}
